// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.wall.responses;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;
import com.vk.api.sdk.objects.groups.GroupFull;
import com.vk.api.sdk.objects.users.User;
import com.vk.api.sdk.objects.wall.WallpostAttachment;

import java.util.List;
import java.util.Objects;

/**
 * ParseAttachedLinkResponse object
 */
public class ParseAttachedLinkResponse implements Validable {
    @SerializedName("data")
    @Required
    private List<WallpostAttachment> data;

    @SerializedName("groups")
    private List<GroupFull> groups;

    @SerializedName("profiles")
    private List<User> profiles;

    public List<WallpostAttachment> getData() {
        return data;
    }

    public ParseAttachedLinkResponse setData(List<WallpostAttachment> data) {
        this.data = data;
        return this;
    }

    public List<GroupFull> getGroups() {
        return groups;
    }

    public ParseAttachedLinkResponse setGroups(List<GroupFull> groups) {
        this.groups = groups;
        return this;
    }

    public List<User> getProfiles() {
        return profiles;
    }

    public ParseAttachedLinkResponse setProfiles(List<User> profiles) {
        this.profiles = profiles;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(data, profiles, groups);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ParseAttachedLinkResponse parseAttachedLinkResponse = (ParseAttachedLinkResponse) o;
        return Objects.equals(data, parseAttachedLinkResponse.data) &&
                Objects.equals(profiles, parseAttachedLinkResponse.profiles) &&
                Objects.equals(groups, parseAttachedLinkResponse.groups);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("ParseAttachedLinkResponse{");
        sb.append("data=").append(data);
        sb.append(", profiles=").append(profiles);
        sb.append(", groups=").append(groups);
        sb.append('}');
        return sb.toString();
    }
}
