// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.callback;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.events.CallbackEvent;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;

import java.util.Objects;

/**
 * AppPayload object
 */
public class AppPayload implements Validable, CallbackEvent {
    @SerializedName("app_id")
    @Required
    private Long appId;

    @SerializedName("payload")
    @Required
    private String payload;

    /**
     * Entity: owner
     */
    @SerializedName("user_id")
    @Required
    private Long userId;

    public Long getAppId() {
        return appId;
    }

    public AppPayload setAppId(Long appId) {
        this.appId = appId;
        return this;
    }

    public String getPayload() {
        return payload;
    }

    public AppPayload setPayload(String payload) {
        this.payload = payload;
        return this;
    }

    public Long getUserId() {
        return userId;
    }

    public AppPayload setUserId(Long userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(payload, appId, userId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AppPayload appPayload = (AppPayload) o;
        return Objects.equals(payload, appPayload.payload) &&
                Objects.equals(userId, appPayload.userId) &&
                Objects.equals(appId, appPayload.appId);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("AppPayload{");
        sb.append("payload='").append(payload).append("'");
        sb.append(", userId=").append(userId);
        sb.append(", appId=").append(appId);
        sb.append('}');
        return sb.toString();
    }
}
