// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.callback;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.events.CallbackEvent;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;

import java.util.Objects;

/**
 * BoardPostDelete object
 */
public class BoardPostDelete implements Validable, CallbackEvent {
    /**
     * Entity: owner
     */
    @SerializedName("deleter_id")
    private Long deleterId;

    @SerializedName("id")
    @Required
    private Integer id;

    @SerializedName("topic_id")
    @Required
    private Integer topicId;

    /**
     * Entity: owner
     */
    @SerializedName("topic_owner_id")
    @Required
    private Long topicOwnerId;

    public Long getDeleterId() {
        return deleterId;
    }

    public BoardPostDelete setDeleterId(Long deleterId) {
        this.deleterId = deleterId;
        return this;
    }

    public Integer getId() {
        return id;
    }

    public BoardPostDelete setId(Integer id) {
        this.id = id;
        return this;
    }

    public Integer getTopicId() {
        return topicId;
    }

    public BoardPostDelete setTopicId(Integer topicId) {
        this.topicId = topicId;
        return this;
    }

    public Long getTopicOwnerId() {
        return topicOwnerId;
    }

    public BoardPostDelete setTopicOwnerId(Long topicOwnerId) {
        this.topicOwnerId = topicOwnerId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(topicId, topicOwnerId, id, deleterId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BoardPostDelete boardPostDelete = (BoardPostDelete) o;
        return Objects.equals(topicOwnerId, boardPostDelete.topicOwnerId) &&
                Objects.equals(deleterId, boardPostDelete.deleterId) &&
                Objects.equals(id, boardPostDelete.id) &&
                Objects.equals(topicId, boardPostDelete.topicId);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("BoardPostDelete{");
        sb.append("topicOwnerId=").append(topicOwnerId);
        sb.append(", deleterId=").append(deleterId);
        sb.append(", id=").append(id);
        sb.append(", topicId=").append(topicId);
        sb.append('}');
        return sb.toString();
    }
}
