// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.callback;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.events.CallbackEvent;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;

import java.util.Objects;

/**
 * GroupChangeSettings object
 */
public class GroupChangeSettings implements Validable, CallbackEvent {
    @SerializedName("changes")
    private GroupSettingsChanges changes;

    /**
     * Entity: owner
     */
    @SerializedName("user_id")
    @Required
    private Long userId;

    public GroupSettingsChanges getChanges() {
        return changes;
    }

    public GroupChangeSettings setChanges(GroupSettingsChanges changes) {
        this.changes = changes;
        return this;
    }

    public Long getUserId() {
        return userId;
    }

    public GroupChangeSettings setUserId(Long userId) {
        this.userId = userId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(changes, userId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GroupChangeSettings groupChangeSettings = (GroupChangeSettings) o;
        return Objects.equals(userId, groupChangeSettings.userId) &&
                Objects.equals(changes, groupChangeSettings.changes);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("GroupChangeSettings{");
        sb.append("userId=").append(userId);
        sb.append(", changes=").append(changes);
        sb.append('}');
        return sb.toString();
    }
}
