// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.callback;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.events.CallbackEvent;
import com.vk.api.sdk.objects.Validable;

import java.util.Objects;

/**
 * GroupSettingsChangesStringValues object
 */
public class GroupSettingsChangesStringValues implements Validable, CallbackEvent {
    @SerializedName("new_value")
    private String newValue;

    @SerializedName("old_value")
    private String oldValue;

    public String getNewValue() {
        return newValue;
    }

    public GroupSettingsChangesStringValues setNewValue(String newValue) {
        this.newValue = newValue;
        return this;
    }

    public String getOldValue() {
        return oldValue;
    }

    public GroupSettingsChangesStringValues setOldValue(String oldValue) {
        this.oldValue = oldValue;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(newValue, oldValue);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GroupSettingsChangesStringValues groupSettingsChangesStringValues = (GroupSettingsChangesStringValues) o;
        return Objects.equals(oldValue, groupSettingsChangesStringValues.oldValue) &&
                Objects.equals(newValue, groupSettingsChangesStringValues.newValue);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("GroupSettingsChangesStringValues{");
        sb.append("oldValue='").append(oldValue).append("'");
        sb.append(", newValue='").append(newValue).append("'");
        sb.append('}');
        return sb.toString();
    }
}
