// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.callback;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.events.CallbackEvent;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;
import com.vk.api.sdk.objects.wall.WallComment;

import java.util.Objects;

/**
 * PhotoComment object
 */
public class PhotoComment extends WallComment implements Validable, CallbackEvent {
    /**
     * Entity: owner
     */
    @SerializedName("photo_owner_id")
    @Required
    private Long photoOwnerId;

    public Long getPhotoOwnerId() {
        return photoOwnerId;
    }

    public PhotoComment setPhotoOwnerId(Long photoOwnerId) {
        this.photoOwnerId = photoOwnerId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(photoOwnerId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PhotoComment photoComment = (PhotoComment) o;
        return Objects.equals(photoOwnerId, photoComment.photoOwnerId);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("PhotoComment{");
        sb.append("photoOwnerId=").append(photoOwnerId);
        sb.append('}');
        return sb.toString();
    }
}
