// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.callback;

import com.vk.api.sdk.events.CallbackEvent;
import com.vk.api.sdk.objects.photos.Photo;

public class PhotoNew extends Photo implements CallbackEvent {
}
