// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.callback;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.events.CallbackEvent;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;

import java.util.Objects;

/**
 * VideoCommentDelete object
 */
public class VideoCommentDelete implements Validable, CallbackEvent {
    /**
     * Entity: owner
     */
    @SerializedName("deleter_id")
    @Required
    private Long deleterId;

    @SerializedName("id")
    @Required
    private Integer id;

    /**
     * Entity: owner
     */
    @SerializedName("owner_id")
    @Required
    private Long ownerId;

    @SerializedName("video_id")
    @Required
    private Integer videoId;

    public Long getDeleterId() {
        return deleterId;
    }

    public VideoCommentDelete setDeleterId(Long deleterId) {
        this.deleterId = deleterId;
        return this;
    }

    public Integer getId() {
        return id;
    }

    public VideoCommentDelete setId(Integer id) {
        this.id = id;
        return this;
    }

    public Long getOwnerId() {
        return ownerId;
    }

    public VideoCommentDelete setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
        return this;
    }

    public Integer getVideoId() {
        return videoId;
    }

    public VideoCommentDelete setVideoId(Integer videoId) {
        this.videoId = videoId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(videoId, id, ownerId, deleterId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        VideoCommentDelete videoCommentDelete = (VideoCommentDelete) o;
        return Objects.equals(ownerId, videoCommentDelete.ownerId) &&
                Objects.equals(deleterId, videoCommentDelete.deleterId) &&
                Objects.equals(id, videoCommentDelete.id) &&
                Objects.equals(videoId, videoCommentDelete.videoId);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("VideoCommentDelete{");
        sb.append("ownerId=").append(ownerId);
        sb.append(", deleterId=").append(deleterId);
        sb.append(", id=").append(id);
        sb.append(", videoId=").append(videoId);
        sb.append('}');
        return sb.toString();
    }
}
