// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.callback;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.events.CallbackEvent;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.wall.WallComment;

import java.util.Objects;

/**
 * VideoComment object
 */
public class VideoComment extends WallComment implements Validable, CallbackEvent {
    /**
     * Entity: owner
     */
    @SerializedName("video_owner_id")
    private Long videoOwnerId;

    public Long getVideoOwnerId() {
        return videoOwnerId;
    }

    public VideoComment setVideoOwnerId(Long videoOwnerId) {
        this.videoOwnerId = videoOwnerId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(videoOwnerId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        VideoComment videoComment = (VideoComment) o;
        return Objects.equals(videoOwnerId, videoComment.videoOwnerId);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("VideoComment{");
        sb.append("videoOwnerId=").append(videoOwnerId);
        sb.append('}');
        return sb.toString();
    }
}
