// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.callback;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.events.CallbackEvent;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;

import java.util.Objects;

/**
 * VkpayTransaction object
 */
public class VkpayTransaction implements Validable, CallbackEvent {
    @SerializedName("amount")
    @Required
    private Integer amount;

    @SerializedName("date")
    @Required
    private Integer date;

    @SerializedName("description")
    @Required
    private String description;

    /**
     * Entity: owner
     */
    @SerializedName("from_id")
    @Required
    private Long fromId;

    @SerializedName("payload")
    private String payload;

    public Integer getAmount() {
        return amount;
    }

    public VkpayTransaction setAmount(Integer amount) {
        this.amount = amount;
        return this;
    }

    public Integer getDate() {
        return date;
    }

    public VkpayTransaction setDate(Integer date) {
        this.date = date;
        return this;
    }

    public String getDescription() {
        return description;
    }

    public VkpayTransaction setDescription(String description) {
        this.description = description;
        return this;
    }

    public Long getFromId() {
        return fromId;
    }

    public VkpayTransaction setFromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public String getPayload() {
        return payload;
    }

    public VkpayTransaction setPayload(String payload) {
        this.payload = payload;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(date, amount, payload, description, fromId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        VkpayTransaction vkpayTransaction = (VkpayTransaction) o;
        return Objects.equals(date, vkpayTransaction.date) &&
                Objects.equals(amount, vkpayTransaction.amount) &&
                Objects.equals(fromId, vkpayTransaction.fromId) &&
                Objects.equals(payload, vkpayTransaction.payload) &&
                Objects.equals(description, vkpayTransaction.description);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("VkpayTransaction{");
        sb.append("date=").append(date);
        sb.append(", amount=").append(amount);
        sb.append(", fromId=").append(fromId);
        sb.append(", payload='").append(payload).append("'");
        sb.append(", description='").append(description).append("'");
        sb.append('}');
        return sb.toString();
    }
}
