// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.notifications;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

public enum NotificationInnerType implements EnumParam<String> {
    @SerializedName("notifications_notification")
    NOTIFICATIONS_NOTIFICATION("notifications_notification");

    private final String value;

    NotificationInnerType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toLowerCase();
    }
}
