// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.groups.responses;

import com.vk.api.sdk.objects.groups.LongPollServer;

public class GetLongPollServerResponse extends LongPollServer {
}
