// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.groups.responses;

import com.vk.api.sdk.objects.groups.MemberStatus;

public class IsMemberUserIdsResponse extends MemberStatus {
}
