// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.prettycards;

import com.google.gson.*;
import com.vk.api.sdk.objects.base.LinkButton;
import com.vk.api.sdk.oneofs.StringOneOf;

import java.lang.reflect.Type;

public interface ButtonOneOf {
    default LinkButton getPrettycardsButtonOneOfAsLinkButton() {
        return (LinkButton) this;
    }

    default StringOneOf getPrettycardsButtonOneOfAsString() {
        return (StringOneOf) this;
    }

    class Deserializer implements JsonDeserializer<ButtonOneOf> {
        @Override
        public ButtonOneOf deserialize(JsonElement json, Type typeOfT,
                JsonDeserializationContext context) throws JsonParseException {
            String errorTrace = "";
            try {
                String jsonValue = json.getAsString();
                StringOneOf result = new StringOneOf();
                result.value = jsonValue;
                return result;
            } catch (Exception e) {
                // Failed to deserialize ButtonOneOf object from JSON as String
                errorTrace = e.getLocalizedMessage();
            }
            try {
                JsonObject data = json.getAsJsonObject();
                return context.deserialize(data, LinkButton.class);
            } catch (Exception e) {
                // Failed to deserialize LinkButton object from JSON
                errorTrace = e.getLocalizedMessage();
            }
            throw new JsonParseException("Failed to deserialize ButtonOneOf object from JSON" + errorTrace);
        }
    }
}
