// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.prettycards;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

public enum PrettyCardInnerType implements EnumParam<String> {
    @SerializedName("prettyCards_prettyCard")
    PRETTYCARDS_PRETTYCARD("prettyCards_prettyCard");

    private final String value;

    PrettyCardInnerType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toLowerCase();
    }
}
