// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.market.responses;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;
import com.vk.api.sdk.objects.photos.Photo;

import java.util.Objects;

/**
 * PhotoIdResponse object
 */
public class PhotoIdResponse implements Validable {
    @SerializedName("photo")
    private Photo photo;

    /**
     * Photo ID
     */
    @SerializedName("photo_id")
    @Required
    private Integer photoId;

    public Photo getPhoto() {
        return photo;
    }

    public PhotoIdResponse setPhoto(Photo photo) {
        this.photo = photo;
        return this;
    }

    public Integer getPhotoId() {
        return photoId;
    }

    public PhotoIdResponse setPhotoId(Integer photoId) {
        this.photoId = photoId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(photoId, photo);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PhotoIdResponse photoIdResponse = (PhotoIdResponse) o;
        return Objects.equals(photoId, photoIdResponse.photoId) &&
                Objects.equals(photo, photoIdResponse.photo);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("PhotoIdResponse{");
        sb.append("photoId=").append(photoId);
        sb.append(", photo=").append(photo);
        sb.append('}');
        return sb.toString();
    }
}
