// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.video.responses;

import com.vk.api.sdk.objects.video.VideoAlbumFull;

public class GetAlbumByIdResponse extends VideoAlbumFull {
}
