// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.video.responses;

import com.vk.api.sdk.objects.video.LiveCategory;

public class LiveGetCategoriesResponse extends LiveCategory {
}
