// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.video.responses;

import com.vk.api.sdk.objects.video.SaveResult;

public class SaveResponse extends SaveResult {
}
