// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.secure.responses;

import com.vk.api.sdk.objects.secure.GiveEventStickerItem;

public class GiveEventStickerResponse extends GiveEventStickerItem {
}
