// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.stories.responses;

import com.vk.api.sdk.objects.stories.StoryStats;

public class GetStatsResponse extends StoryStats {
}
