// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.stats.responses;

import com.vk.api.sdk.objects.stats.Period;

public class GetResponse extends Period {
}
