// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.prettycards.responses;

import com.vk.api.sdk.objects.prettycards.PrettyCardOrError;

public interface GetByIdResponse extends PrettyCardOrError {
}
