// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.base;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;

import java.util.Objects;

/**
 * LikesInfo object
 */
public class LikesInfo implements Validable {
    /**
     * Information whether post author liked the reply
     */
    @SerializedName("author_liked")
    private Boolean authorLiked;

    /**
     * Information whether current user can like the post
     */
    @SerializedName("can_like")
    @Required
    private BoolInt canLike;

    /**
     * Whether user can like comment as author
     */
    @SerializedName("can_like_as_author")
    private BoolInt canLikeAsAuthor;

    /**
     * Whether current owner of the group can like the reply
     */
    @SerializedName("can_like_by_group")
    private BoolInt canLikeByGroup;

    /**
     * Information whether current user can repost
     */
    @SerializedName("can_publish")
    private BoolInt canPublish;

    /**
     * Likes number
     */
    @SerializedName("count")
    @Required
    private Integer count;

    /**
     * Information whether group liked the reply
     */
    @SerializedName("group_liked")
    private Boolean groupLiked;

    /**
     * Remove repost feature for post
     */
    @SerializedName("repost_disabled")
    private Boolean repostDisabled;

    /**
     * Information whether current uer has liked the post
     */
    @SerializedName("user_likes")
    @Required
    private BoolInt userLikes;

    public Boolean getAuthorLiked() {
        return authorLiked;
    }

    public LikesInfo setAuthorLiked(Boolean authorLiked) {
        this.authorLiked = authorLiked;
        return this;
    }

    public boolean canLike() {
        return canLike == BoolInt.YES;
    }

    public BoolInt getCanLike() {
        return canLike;
    }

    public boolean canLikeAsAuthor() {
        return canLikeAsAuthor == BoolInt.YES;
    }

    public BoolInt getCanLikeAsAuthor() {
        return canLikeAsAuthor;
    }

    public boolean canLikeByGroup() {
        return canLikeByGroup == BoolInt.YES;
    }

    public BoolInt getCanLikeByGroup() {
        return canLikeByGroup;
    }

    public boolean canPublish() {
        return canPublish == BoolInt.YES;
    }

    public BoolInt getCanPublish() {
        return canPublish;
    }

    public Integer getCount() {
        return count;
    }

    public LikesInfo setCount(Integer count) {
        this.count = count;
        return this;
    }

    public Boolean getGroupLiked() {
        return groupLiked;
    }

    public LikesInfo setGroupLiked(Boolean groupLiked) {
        this.groupLiked = groupLiked;
        return this;
    }

    public Boolean getRepostDisabled() {
        return repostDisabled;
    }

    public LikesInfo setRepostDisabled(Boolean repostDisabled) {
        this.repostDisabled = repostDisabled;
        return this;
    }

    public boolean isUserLikes() {
        return userLikes == BoolInt.YES;
    }

    public BoolInt getUserLikes() {
        return userLikes;
    }

    @Override
    public int hashCode() {
        return Objects.hash(canLikeAsAuthor, authorLiked, canLike, canPublish, repostDisabled, count, canLikeByGroup, userLikes, groupLiked);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        LikesInfo likesInfo = (LikesInfo) o;
        return Objects.equals(canLikeAsAuthor, likesInfo.canLikeAsAuthor) &&
                Objects.equals(userLikes, likesInfo.userLikes) &&
                Objects.equals(canPublish, likesInfo.canPublish) &&
                Objects.equals(canLike, likesInfo.canLike) &&
                Objects.equals(repostDisabled, likesInfo.repostDisabled) &&
                Objects.equals(canLikeByGroup, likesInfo.canLikeByGroup) &&
                Objects.equals(count, likesInfo.count) &&
                Objects.equals(groupLiked, likesInfo.groupLiked) &&
                Objects.equals(authorLiked, likesInfo.authorLiked);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("LikesInfo{");
        sb.append("canLikeAsAuthor=").append(canLikeAsAuthor);
        sb.append(", userLikes=").append(userLikes);
        sb.append(", canPublish=").append(canPublish);
        sb.append(", canLike=").append(canLike);
        sb.append(", repostDisabled=").append(repostDisabled);
        sb.append(", canLikeByGroup=").append(canLikeByGroup);
        sb.append(", count=").append(count);
        sb.append(", groupLiked=").append(groupLiked);
        sb.append(", authorLiked=").append(authorLiked);
        sb.append('}');
        return sb.toString();
    }
}
