// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.base;

import com.google.gson.*;
import com.vk.api.sdk.objects.market.MarketCategoryNested;
import com.vk.api.sdk.oneofs.StringOneOf;

import java.lang.reflect.Type;

public interface LinkProductCategory {
    default StringOneOf getBaseLinkProductCategoryAsString() {
        return (StringOneOf) this;
    }

    default MarketCategoryNested getBaseLinkProductCategoryAsMarketCategoryNested() {
        return (MarketCategoryNested) this;
    }

    class Deserializer implements JsonDeserializer<LinkProductCategory> {
        @Override
        public LinkProductCategory deserialize(JsonElement json, Type typeOfT,
                JsonDeserializationContext context) throws JsonParseException {
            String errorTrace = "";
            try {
                String jsonValue = json.getAsString();
                StringOneOf result = new StringOneOf();
                result.value = jsonValue;
                return result;
            } catch (Exception e) {
                // Failed to deserialize LinkProductCategory object from JSON as String
                errorTrace = e.getLocalizedMessage();
            }
            try {
                JsonObject data = json.getAsJsonObject();
                return context.deserialize(data, MarketCategoryNested.class);
            } catch (Exception e) {
                // Failed to deserialize MarketCategoryNested object from JSON
                errorTrace = e.getLocalizedMessage();
            }
            throw new JsonParseException("Failed to deserialize LinkProductCategory object from JSON" + errorTrace);
        }
    }
}
