// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.base;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

public enum StickerNewInnerType implements EnumParam<String> {
    @SerializedName("base_sticker_new")
    BASE_STICKER_NEW("base_sticker_new");

    private final String value;

    StickerNewInnerType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toLowerCase();
    }
}
