// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.stats;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

public enum TrackVisitorType implements EnumParam<String> {
    @SerializedName("activity")
    ACTIVITY("activity"),

    @SerializedName("close")
    CLOSE("close"),

    @SerializedName("open")
    OPEN("open");

    private final String value;

    TrackVisitorType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toLowerCase();
    }
}
