// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.photos.responses;

import com.vk.api.sdk.objects.photos.Photo;

public class SaveMarketPhotoResponse extends Photo {
}
