// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.apps.responses;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;

import java.util.Objects;

/**
 * AddSnippetResponse object
 */
public class AddSnippetResponse implements Validable {
    @SerializedName("snippet_id")
    @Required
    private Integer snippetId;

    public Integer getSnippetId() {
        return snippetId;
    }

    public AddSnippetResponse setSnippetId(Integer snippetId) {
        this.snippetId = snippetId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(snippetId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AddSnippetResponse addSnippetResponse = (AddSnippetResponse) o;
        return Objects.equals(snippetId, addSnippetResponse.snippetId);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("AddSnippetResponse{");
        sb.append("snippetId=").append(snippetId);
        sb.append('}');
        return sb.toString();
    }
}
