// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.apps.responses;

import com.vk.api.sdk.objects.apps.TestingGroup;

public class GetTestingGroupsResponse extends TestingGroup {
}
