// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.pages.responses;

import com.vk.api.sdk.objects.pages.WikipageHistory;

public class GetHistoryResponse extends WikipageHistory {
}
