// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.pages.responses;

import com.vk.api.sdk.objects.pages.WikipageFull;

public class GetVersionResponse extends WikipageFull {
}
