// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.groups;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

public enum GroupFullAgeLimits implements EnumParam<Integer> {
    @SerializedName("1")
    NO(1),

    @SerializedName("2")
    OVER_16(2),

    @SerializedName("3")
    OVER_18(3);

    private final Integer value;

    GroupFullAgeLimits(Integer value) {
        this.value = value;
    }

    public Integer getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toString().toLowerCase();
    }
}
