// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.groups;

import com.vk.api.sdk.objects.base.BaseObject;

public class SectionsListItem extends BaseObject {
}
