// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.friends.responses;

import com.vk.api.sdk.objects.friends.FriendExtendedStatus;

public class AreFriendsExtendedResponse extends FriendExtendedStatus {
}
