// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.friends.responses;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

/**
 * Returns 1 if out request has been canceled
 */
public enum DeleteResponseOutRequestDeleted implements EnumParam<Integer> {
    @SerializedName("1")
    OK(1);

    private final Integer value;

    DeleteResponseOutRequestDeleted(Integer value) {
        this.value = value;
    }

    public Integer getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toString().toLowerCase();
    }
}
