// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.fave.responses;

import com.vk.api.sdk.objects.fave.Tag;

public class AddTagResponse extends Tag {
}
