// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.oneofs;

import com.google.gson.annotations.SerializedName;

public class IntegerOneOf {
    @SerializedName("value")
    public Integer value;
}
