// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.oneofs;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.base.LinkProductCategory;
import com.vk.api.sdk.objects.prettycards.ButtonOneOf;

public class StringOneOf implements ButtonOneOf, LinkProductCategory {
    @SerializedName("value")
    public String value;
}
