// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.appwidgets.responses;

import com.vk.api.sdk.objects.appwidgets.Photos;

public class GetGroupImagesResponse extends Photos {
}
