// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.appwidgets.responses;

import com.vk.api.sdk.objects.appwidgets.Photo;

public class SaveGroupImageResponse extends Photo {
}
