// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.base.responses;

import com.vk.api.sdk.objects.base.UploadServer;

public class GetUploadServerResponse extends UploadServer {
}
