// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.status.responses;

import com.vk.api.sdk.objects.status.Status;

public class GetResponse extends Status {
}
