// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.polls;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.users.UserFull;

import java.util.List;
import java.util.Objects;

/**
 * PollExtended object
 */
public class PollExtended extends Poll implements Validable {
    @SerializedName("profiles")
    private List<UserFull> profiles;

    public List<UserFull> getProfiles() {
        return profiles;
    }

    public PollExtended setProfiles(List<UserFull> profiles) {
        this.profiles = profiles;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(profiles);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PollExtended pollExtended = (PollExtended) o;
        return Objects.equals(profiles, pollExtended.profiles);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("PollExtended{");
        sb.append("profiles=").append(profiles);
        sb.append('}');
        return sb.toString();
    }
}
