// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.messages.responses;

import com.vk.api.sdk.objects.messages.GetConversationMembers;

public class GetConversationMembersResponse extends GetConversationMembers {
}
