// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAuthFloodErrorException extends ApiException {
    public static final Integer ERROR_CODE = 1105;

    public static final String ERROR_DESCRIPTION = "Too many auth attempts, try again later";

    public ApiAuthFloodErrorException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAuthFloodErrorException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
