// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAdsPermissionException extends ApiException {
    public static final Integer ERROR_CODE = 600;

    public static final String ERROR_DESCRIPTION = "Permission denied. You have no access to operations specified with given object(s)";

    public ApiAdsPermissionException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAdsPermissionException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
