// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAccessNoteCommentException extends ApiException {
    public static final Integer ERROR_CODE = 182;

    public static final String ERROR_DESCRIPTION = "You can't comment this note";

    public ApiAccessNoteCommentException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAccessNoteCommentException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
