// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAppAuthException extends ApiException {
    public static final Integer ERROR_CODE = 28;

    public static final String ERROR_DESCRIPTION = "Application authorization failed";

    public ApiAppAuthException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAppAuthException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
