// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAdsLookalikeRequestMaxCountPerDayReachedException extends ApiException {
    public static final Integer ERROR_CODE = 631;

    public static final String ERROR_DESCRIPTION = "Max count of lookalike requests per day reached";

    public ApiAdsLookalikeRequestMaxCountPerDayReachedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAdsLookalikeRequestMaxCountPerDayReachedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
