// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAccessNoteException extends ApiException {
    public static final Integer ERROR_CODE = 181;

    public static final String ERROR_DESCRIPTION = "Access to note denied";

    public ApiAccessNoteException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAccessNoteException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
