// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAccessAlbumException extends ApiException {
    public static final Integer ERROR_CODE = 200;

    public static final String ERROR_DESCRIPTION = "Access denied";

    public ApiAccessAlbumException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAccessAlbumException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
