// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAccessCommentException extends ApiException {
    public static final Integer ERROR_CODE = 183;

    public static final String ERROR_DESCRIPTION = "Access to comment denied";

    public ApiAccessCommentException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAccessCommentException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
