// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAuthHttpsException extends ApiException {
    public static final Integer ERROR_CODE = 16;

    public static final String ERROR_DESCRIPTION = "HTTP authorization failed";

    public ApiAuthHttpsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAuthHttpsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
