// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAsrInvalidHashException extends ApiException {
    public static final Integer ERROR_CODE = 7703;

    public static final String ERROR_DESCRIPTION = "Invalid hash";

    public ApiAsrInvalidHashException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAsrInvalidHashException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
