// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAuthAnonymousTokenIsInvalidException extends ApiException {
    public static final Integer ERROR_CODE = 1116;

    public static final String ERROR_DESCRIPTION = "Anonymous token is invalid";

    public ApiAuthAnonymousTokenIsInvalidException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAuthAnonymousTokenIsInvalidException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
