// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAdsPartialSuccessException extends ApiException {
    public static final Integer ERROR_CODE = 602;

    public static final String ERROR_DESCRIPTION = "Some part of the request has not been completed";

    public ApiAdsPartialSuccessException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAdsPartialSuccessException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
