// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAuthAnonymousTokenIpMismatchException extends ApiException {
    public static final Integer ERROR_CODE = 1118;

    public static final String ERROR_DESCRIPTION = "Anonymous token ip mismatch";

    public ApiAuthAnonymousTokenIpMismatchException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAuthAnonymousTokenIpMismatchException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
