// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAuthAccessTokenHasExpiredException extends ApiException {
    public static final Integer ERROR_CODE = 1117;

    public static final String ERROR_DESCRIPTION = "Access token has expired";

    public ApiAuthAccessTokenHasExpiredException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAuthAccessTokenHasExpiredException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
