// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAdditionalSignupRequiredException extends ApiException {
    public static final Integer ERROR_CODE = 41;

    public static final String ERROR_DESCRIPTION = "Additional signup required";

    public ApiAdditionalSignupRequiredException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAdditionalSignupRequiredException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
