// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAppsTooManySnippetsException extends ApiException {
    public static final Integer ERROR_CODE = 11005;

    public static final String ERROR_DESCRIPTION = "Too many snippets";

    public ApiAppsTooManySnippetsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAppsTooManySnippetsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
