// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAdsLookalikeRequestAudienceTooSmallException extends ApiException {
    public static final Integer ERROR_CODE = 632;

    public static final String ERROR_DESCRIPTION = "Given audience is too small";

    public ApiAdsLookalikeRequestAudienceTooSmallException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAdsLookalikeRequestAudienceTooSmallException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
