// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAdsLookalikeRequestAudienceTooLargeException extends ApiException {
    public static final Integer ERROR_CODE = 633;

    public static final String ERROR_DESCRIPTION = "Given audience is too large";

    public ApiAdsLookalikeRequestAudienceTooLargeException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAdsLookalikeRequestAudienceTooLargeException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
