// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAppsEmptySnippetDataException extends ApiException {
    public static final Integer ERROR_CODE = 11004;

    public static final String ERROR_DESCRIPTION = "Empty snippet data";

    public ApiAppsEmptySnippetDataException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAppsEmptySnippetDataException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
