// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiActionFailedException extends ApiException {
    public static final Integer ERROR_CODE = 106;

    public static final String ERROR_DESCRIPTION = "Unable to process action";

    public ApiActionFailedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiActionFailedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
