// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAdsLookalikeRequestExportRetargetingGroupLimitException extends ApiException {
    public static final Integer ERROR_CODE = 636;

    public static final String ERROR_DESCRIPTION = "Max count of retargeting groups reached";

    public ApiAdsLookalikeRequestExportRetargetingGroupLimitException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAdsLookalikeRequestExportRetargetingGroupLimitException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
