// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAccessGroupException extends ApiException {
    public static final Integer ERROR_CODE = 203;

    public static final String ERROR_DESCRIPTION = "Access to group denied";

    public ApiAccessGroupException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAccessGroupException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
