// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAppsNotFoundSnippetException extends ApiException {
    public static final Integer ERROR_CODE = 11006;

    public static final String ERROR_DESCRIPTION = "Not found snippet";

    public ApiAppsNotFoundSnippetException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAppsNotFoundSnippetException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
