// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAppsSubscriptionNotFoundException extends ApiException {
    public static final Integer ERROR_CODE = 1256;

    public static final String ERROR_DESCRIPTION = "Subscription not found";

    public ApiAppsSubscriptionNotFoundException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAppsSubscriptionNotFoundException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
