// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAccessGroupsException extends ApiException {
    public static final Integer ERROR_CODE = 260;

    public static final String ERROR_DESCRIPTION = "Access to the groups list is denied due to the user's privacy settings";

    public ApiAccessGroupsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAccessGroupsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
