// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAuthException extends ApiException {
    public static final Integer ERROR_CODE = 5;

    public static final String ERROR_DESCRIPTION = "User authorization failed";

    public ApiAuthException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAuthException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
