// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAsrAudioDurationFloodedException extends ApiException {
    public static final Integer ERROR_CODE = 7701;

    public static final String ERROR_DESCRIPTION = "Total audio duration limit reached";

    public ApiAsrAudioDurationFloodedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAsrAudioDurationFloodedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
