// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAppsSubscriptionInvalidStatusException extends ApiException {
    public static final Integer ERROR_CODE = 1257;

    public static final String ERROR_DESCRIPTION = "Subscription is in invalid status";

    public ApiAppsSubscriptionInvalidStatusException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAppsSubscriptionInvalidStatusException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
