// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAlbumsLimitException extends ApiException {
    public static final Integer ERROR_CODE = 302;

    public static final String ERROR_DESCRIPTION = "Albums number limit is reached";

    public ApiAlbumsLimitException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAlbumsLimitException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
