// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiAuthAnonymousTokenHasExpiredException extends ApiException {
    public static final Integer ERROR_CODE = 1114;

    public static final String ERROR_DESCRIPTION = "Anonymous token has expired";

    public ApiAuthAnonymousTokenHasExpiredException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiAuthAnonymousTokenHasExpiredException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
