// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiBlockedException extends ApiException {
    public static final Integer ERROR_CODE = 19;

    public static final String ERROR_DESCRIPTION = "Content blocked";

    public ApiBlockedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiBlockedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
