// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiCaptchaException extends ApiException {
    public static final Integer ERROR_CODE = 14;

    public static final String ERROR_DESCRIPTION = "Captcha needed";

    public ApiCaptchaException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiCaptchaException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
