// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiClientUpdateNeededException extends ApiException {
    public static final Integer ERROR_CODE = 35;

    public static final String ERROR_DESCRIPTION = "Client update needed";

    public ApiClientUpdateNeededException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiClientUpdateNeededException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
