// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiCuaConfirmationRequiredException extends ApiException {
    public static final Integer ERROR_CODE = 11500;

    public static final String ERROR_DESCRIPTION = "CheckUserAction confirmation required";

    public ApiCuaConfirmationRequiredException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiCuaConfirmationRequiredException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
