// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiCallbackApiServersLimitException extends ApiException {
    public static final Integer ERROR_CODE = 2000;

    public static final String ERROR_DESCRIPTION = "Servers number limit is reached";

    public ApiCallbackApiServersLimitException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiCallbackApiServersLimitException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
