// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiEnabledInTestException extends ApiException {
    public static final Integer ERROR_CODE = 11;

    public static final String ERROR_DESCRIPTION = "In test mode application should be disabled or user should be authorized";

    public ApiEnabledInTestException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiEnabledInTestException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
