// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiFriendsAddInEnemyException extends ApiException {
    public static final Integer ERROR_CODE = 175;

    public static final String ERROR_DESCRIPTION = "Cannot add this user to friends as they have put you on their blacklist";

    public ApiFriendsAddInEnemyException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiFriendsAddInEnemyException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
