// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiFriendsListLimitException extends ApiException {
    public static final Integer ERROR_CODE = 173;

    public static final String ERROR_DESCRIPTION = "Reached the maximum number of lists";

    public ApiFriendsListLimitException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiFriendsListLimitException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
