// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiFriendsAddEnemyException extends ApiException {
    public static final Integer ERROR_CODE = 176;

    public static final String ERROR_DESCRIPTION = "Cannot add this user to friends as you put him on blacklist";

    public ApiFriendsAddEnemyException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiFriendsAddEnemyException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
