// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiFaveAliexpressTagException extends ApiException {
    public static final Integer ERROR_CODE = 3800;

    public static final String ERROR_DESCRIPTION = "Can't set AliExpress tag to this type of object";

    public ApiFaveAliexpressTagException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiFaveAliexpressTagException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
