// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiFriendsAddNotFoundException extends ApiException {
    public static final Integer ERROR_CODE = 177;

    public static final String ERROR_DESCRIPTION = "Cannot add this user to friends as user not found";

    public ApiFriendsAddNotFoundException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiFriendsAddNotFoundException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
