// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiFriendsAddYourselfException extends ApiException {
    public static final Integer ERROR_CODE = 174;

    public static final String ERROR_DESCRIPTION = "Cannot add user himself as friend";

    public ApiFriendsAddYourselfException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiFriendsAddYourselfException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
