// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiFriendsTooManyFriendsException extends ApiException {
    public static final Integer ERROR_CODE = 242;

    public static final String ERROR_DESCRIPTION = "Too many friends";

    public ApiFriendsTooManyFriendsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiFriendsTooManyFriendsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
