// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiGroupAppIsNotInstalledInCommunityException extends ApiException {
    public static final Integer ERROR_CODE = 711;

    public static final String ERROR_DESCRIPTION = "Application is not installed in community";

    public ApiGroupAppIsNotInstalledInCommunityException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiGroupAppIsNotInstalledInCommunityException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
