// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiGroupInviteLinksNotValidException extends ApiException {
    public static final Integer ERROR_CODE = 714;

    public static final String ERROR_DESCRIPTION = "Invite link is invalid - expired, deleted or not exists";

    public ApiGroupInviteLinksNotValidException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiGroupInviteLinksNotValidException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
