// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiGroupHostNeed2faException extends ApiException {
    public static final Integer ERROR_CODE = 704;

    public static final String ERROR_DESCRIPTION = "User needs to enable 2FA for this action";

    public ApiGroupHostNeed2faException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiGroupHostNeed2faException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
