// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiGroupNotInClubException extends ApiException {
    public static final Integer ERROR_CODE = 701;

    public static final String ERROR_DESCRIPTION = "User should be in club";

    public ApiGroupNotInClubException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiGroupNotInClubException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
