// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiGroupAuthException extends ApiException {
    public static final Integer ERROR_CODE = 27;

    public static final String ERROR_DESCRIPTION = "Group authorization failed";

    public ApiGroupAuthException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiGroupAuthException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
