// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiLikesReactionCanNotBeAppliedException extends ApiException {
    public static final Integer ERROR_CODE = 232;

    public static final String ERROR_DESCRIPTION = "Reaction can not be applied to the object";

    public ApiLikesReactionCanNotBeAppliedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiLikesReactionCanNotBeAppliedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
