// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesChatUserLeftException extends ApiException {
    public static final Integer ERROR_CODE = 922;

    public static final String ERROR_DESCRIPTION = "You left this chat";

    public ApiMessagesChatUserLeftException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesChatUserLeftException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
