// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesKeyboardInvalidException extends ApiException {
    public static final Integer ERROR_CODE = 911;

    public static final String ERROR_DESCRIPTION = "Keyboard format is invalid";

    public ApiMessagesKeyboardInvalidException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesKeyboardInvalidException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
