// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesIntentLimitOverflowException extends ApiException {
    public static final Integer ERROR_CODE = 944;

    public static final String ERROR_DESCRIPTION = "Limits overflow for this intent";

    public ApiMessagesIntentLimitOverflowException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesIntentLimitOverflowException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
