// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesInvalidReactionIdException extends ApiException {
    public static final Integer ERROR_CODE = 1009;

    public static final String ERROR_DESCRIPTION = "Unknown reaction passed";

    public ApiMessagesInvalidReactionIdException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesInvalidReactionIdException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
