// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketGroupingItemsMustHaveDistinctPropertiesException extends ApiException {
    public static final Integer ERROR_CODE = 1426;

    public static final String ERROR_DESCRIPTION = "Item must have distinct properties";

    public ApiMarketGroupingItemsMustHaveDistinctPropertiesException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketGroupingItemsMustHaveDistinctPropertiesException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
