// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesGroupForNotificationsOnlyException extends ApiException {
    public static final Integer ERROR_CODE = 985;

    public static final String ERROR_DESCRIPTION = "Cannot write to notifications only groups";

    public ApiMessagesGroupForNotificationsOnlyException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesGroupForNotificationsOnlyException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
