// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketShopAlreadyEnabledException extends ApiException {
    public static final Integer ERROR_CODE = 1431;

    public static final String ERROR_DESCRIPTION = "Market was already enabled in this group";

    public ApiMarketShopAlreadyEnabledException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketShopAlreadyEnabledException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
