// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesChatUserNotInChatException extends ApiException {
    public static final Integer ERROR_CODE = 935;

    public static final String ERROR_DESCRIPTION = "User not found in chat";

    public ApiMessagesChatUserNotInChatException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesChatUserNotInChatException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
