// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketCommentsClosedException extends ApiException {
    public static final Integer ERROR_CODE = 1401;

    public static final String ERROR_DESCRIPTION = "Comments for this market are closed";

    public ApiMarketCommentsClosedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketCommentsClosedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
