// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesMessageRequestAlreadySentException extends ApiException {
    public static final Integer ERROR_CODE = 939;

    public static final String ERROR_DESCRIPTION = "Message request already sent";

    public ApiMessagesMessageRequestAlreadySentException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesMessageRequestAlreadySentException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
