// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesTooLongMessageException extends ApiException {
    public static final Integer ERROR_CODE = 914;

    public static final String ERROR_DESCRIPTION = "Message is too long";

    public ApiMessagesTooLongMessageException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesTooLongMessageException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
