// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesForbiddenReactionException extends ApiException {
    public static final Integer ERROR_CODE = 1010;

    public static final String ERROR_DESCRIPTION = "This reaction has been disabled";

    public ApiMessagesForbiddenReactionException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesForbiddenReactionException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
