// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMethodAdsException extends ApiException {
    public static final Integer ERROR_CODE = 21;

    public static final String ERROR_DESCRIPTION = "Permission to perform this action is allowed only for standalone and OpenAPI applications";

    public ApiMethodAdsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMethodAdsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
