// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesChatUserNoAccessException extends ApiException {
    public static final Integer ERROR_CODE = 917;

    public static final String ERROR_DESCRIPTION = "You don't have access to this chat";

    public ApiMessagesChatUserNoAccessException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesChatUserNoAccessException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
