// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesReactionsLimitReachedException extends ApiException {
    public static final Integer ERROR_CODE = 1011;

    public static final String ERROR_DESCRIPTION = "Reactions limit for this message has been reached";

    public ApiMessagesReactionsLimitReachedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesReactionsLimitReachedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
