// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketFailedToUnsetAlbumAsMainException extends ApiException {
    public static final Integer ERROR_CODE = 1458;

    public static final String ERROR_DESCRIPTION = "Failed to unset album as main";

    public ApiMarketFailedToUnsetAlbumAsMainException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketFailedToUnsetAlbumAsMainException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
