// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketMaxVariantsLimitExceedException extends ApiException {
    public static final Integer ERROR_CODE = 1419;

    public static final String ERROR_DESCRIPTION = "Max variant limit exceeded";

    public ApiMarketMaxVariantsLimitExceedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketMaxVariantsLimitExceedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
