// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMethodDisabledException extends ApiException {
    public static final Integer ERROR_CODE = 23;

    public static final String ERROR_DESCRIPTION = "This method was disabled";

    public ApiMethodDisabledException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMethodDisabledException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
