// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketPhotosCropInvalidFormatException extends ApiException {
    public static final Integer ERROR_CODE = 1433;

    public static final String ERROR_DESCRIPTION = "Invalid image crop format";

    public ApiMarketPhotosCropInvalidFormatException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketPhotosCropInvalidFormatException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
