// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesChatDisabledException extends ApiException {
    public static final Integer ERROR_CODE = 945;

    public static final String ERROR_DESCRIPTION = "Chat was disabled";

    public ApiMessagesChatDisabledException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesChatDisabledException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
