// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesPeerBlockedReasonByTimeException extends ApiException {
    public static final Integer ERROR_CODE = 950;

    public static final String ERROR_DESCRIPTION = "Can't send message, reply timed out";

    public ApiMessagesPeerBlockedReasonByTimeException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesPeerBlockedReasonByTimeException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
