// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesIntentCantUseException extends ApiException {
    public static final Integer ERROR_CODE = 943;

    public static final String ERROR_DESCRIPTION = "Cannot use this intent";

    public ApiMessagesIntentCantUseException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesIntentCantUseException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
