// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketGroupingAlreadyHasSuchVariantException extends ApiException {
    public static final Integer ERROR_CODE = 1413;

    public static final String ERROR_DESCRIPTION = "Grouping already has such variant";

    public ApiMarketGroupingAlreadyHasSuchVariantException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketGroupingAlreadyHasSuchVariantException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
