// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketPropertyNotFoundException extends ApiException {
    public static final Integer ERROR_CODE = 1417;

    public static final String ERROR_DESCRIPTION = "Property not found";

    public ApiMarketPropertyNotFoundException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketPropertyNotFoundException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
