// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketItemNotFoundException extends ApiException {
    public static final Integer ERROR_CODE = 1403;

    public static final String ERROR_DESCRIPTION = "Item not found";

    public ApiMarketItemNotFoundException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketItemNotFoundException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
