// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketGroupingMustHaveVariantsException extends ApiException {
    public static final Integer ERROR_CODE = 1415;

    public static final String ERROR_DESCRIPTION = "Grouping must have variants";

    public ApiMarketGroupingMustHaveVariantsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketGroupingMustHaveVariantsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
