// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketGroupingItemsWithDifferentPropertiesException extends ApiException {
    public static final Integer ERROR_CODE = 1412;

    public static final String ERROR_DESCRIPTION = "Grouping items with different properties";

    public ApiMarketGroupingItemsWithDifferentPropertiesException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketGroupingItemsWithDifferentPropertiesException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
