// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketCantChangeVkpayStatusException extends ApiException {
    public static final Integer ERROR_CODE = 1430;

    public static final String ERROR_DESCRIPTION = "VK Pay status can not be changed";

    public ApiMarketCantChangeVkpayStatusException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketCantChangeVkpayStatusException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
