// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketItemAlreadyAddedException extends ApiException {
    public static final Integer ERROR_CODE = 1404;

    public static final String ERROR_DESCRIPTION = "Item already added to album";

    public ApiMarketItemAlreadyAddedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketItemAlreadyAddedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
