// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesCantPinOneTimeStoryException extends ApiException {
    public static final Integer ERROR_CODE = 942;

    public static final String ERROR_DESCRIPTION = "Cannot pin one-time story";

    public ApiMessagesCantPinOneTimeStoryException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesCantPinOneTimeStoryException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
