// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesUserNotDonException extends ApiException {
    public static final Integer ERROR_CODE = 962;

    public static final String ERROR_DESCRIPTION = "You can't access donut chat without subscription";

    public ApiMessagesUserNotDonException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesUserNotDonException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
