// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesTooNewPtsException extends ApiException {
    public static final Integer ERROR_CODE = 908;

    public static final String ERROR_DESCRIPTION = "Value of ts or pts is too new";

    public ApiMessagesTooNewPtsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesTooNewPtsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
