// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketGroupingHasOtherPropertiesException extends ApiException {
    public static final Integer ERROR_CODE = 1414;

    public static final String ERROR_DESCRIPTION = "Grouping has other properties";

    public ApiMarketGroupingHasOtherPropertiesException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketGroupingHasOtherPropertiesException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
