// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesMessageCannotBeForwardedException extends ApiException {
    public static final Integer ERROR_CODE = 969;

    public static final String ERROR_DESCRIPTION = "Message cannot be forwarded";

    public ApiMessagesMessageCannotBeForwardedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesMessageCannotBeForwardedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
