// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesCantChangeInviteLinkException extends ApiException {
    public static final Integer ERROR_CODE = 931;

    public static final String ERROR_DESCRIPTION = "You can't change invite link for this chat";

    public ApiMessagesCantChangeInviteLinkException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesCantChangeInviteLinkException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
