// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketVariantNotFoundException extends ApiException {
    public static final Integer ERROR_CODE = 1416;

    public static final String ERROR_DESCRIPTION = "Variant not found";

    public ApiMarketVariantNotFoundException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketVariantNotFoundException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
