// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketInvalidDimensionsException extends ApiException {
    public static final Integer ERROR_CODE = 1429;

    public static final String ERROR_DESCRIPTION = "Specify width, length, height and weight all together";

    public ApiMarketInvalidDimensionsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketInvalidDimensionsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
