// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesEditExpiredException extends ApiException {
    public static final Integer ERROR_CODE = 909;

    public static final String ERROR_DESCRIPTION = "Can't edit this message, because it's too old";

    public ApiMessagesEditExpiredException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesEditExpiredException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
