// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketTooManyItemsException extends ApiException {
    public static final Integer ERROR_CODE = 1405;

    public static final String ERROR_DESCRIPTION = "Too many items";

    public ApiMarketTooManyItemsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketTooManyItemsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
