// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesMemberAccessToGroupDeniedException extends ApiException {
    public static final Integer ERROR_CODE = 947;

    public static final String ERROR_DESCRIPTION = "Can't add user to chat, because user has no access to group";

    public ApiMessagesMemberAccessToGroupDeniedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesMemberAccessToGroupDeniedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
