// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketRestoreTooLateException extends ApiException {
    public static final Integer ERROR_CODE = 1400;

    public static final String ERROR_DESCRIPTION = "Too late for restore";

    public ApiMarketRestoreTooLateException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketRestoreTooLateException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
