// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMethodException extends ApiException {
    public static final Integer ERROR_CODE = 3;

    public static final String ERROR_DESCRIPTION = "Unknown method passed";

    public ApiMethodException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMethodException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
