// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesWritingDisabledForChatException extends ApiException {
    public static final Integer ERROR_CODE = 1012;

    public static final String ERROR_DESCRIPTION = "Writing is disabled for this chat";

    public ApiMessagesWritingDisabledForChatException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesWritingDisabledForChatException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
