// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketVariantValueTooLongException extends ApiException {
    public static final Integer ERROR_CODE = 1423;

    public static final String ERROR_DESCRIPTION = "Variant value is too long";

    public ApiMarketVariantValueTooLongException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketVariantValueTooLongException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
