// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketOrdersNoCartItemsException extends ApiException {
    public static final Integer ERROR_CODE = 1427;

    public static final String ERROR_DESCRIPTION = "Cart is empty";

    public ApiMarketOrdersNoCartItemsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketOrdersNoCartItemsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
