// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketFailedToSetAlbumAsMainException extends ApiException {
    public static final Integer ERROR_CODE = 1457;

    public static final String ERROR_DESCRIPTION = "Failed to set album as main";

    public ApiMarketFailedToSetAlbumAsMainException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketFailedToSetAlbumAsMainException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
