// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMessagesPrivacyException extends ApiException {
    public static final Integer ERROR_CODE = 902;

    public static final String ERROR_DESCRIPTION = "Can't send messages to this user due to their privacy settings";

    public ApiMessagesPrivacyException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMessagesPrivacyException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
