// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketPhotosCropSizeTooLowException extends ApiException {
    public static final Integer ERROR_CODE = 1435;

    public static final String ERROR_DESCRIPTION = "Crop size is less than the minimum";

    public ApiMarketPhotosCropSizeTooLowException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketPhotosCropSizeTooLowException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
