// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketVariantsNotEnabledException extends ApiException {
    public static final Integer ERROR_CODE = 1410;

    public static final String ERROR_DESCRIPTION = "Variants not enabled";

    public ApiMarketVariantsNotEnabledException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketVariantsNotEnabledException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
