// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketTooManyAlbumsException extends ApiException {
    public static final Integer ERROR_CODE = 1407;

    public static final String ERROR_DESCRIPTION = "Too many albums";

    public ApiMarketTooManyAlbumsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketTooManyAlbumsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
