// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiMarketAlbumNotFoundException extends ApiException {
    public static final Integer ERROR_CODE = 1402;

    public static final String ERROR_DESCRIPTION = "Album not found";

    public ApiMarketAlbumNotFoundException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiMarketAlbumNotFoundException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
