// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiNeedConfirmationException extends ApiException {
    public static final Integer ERROR_CODE = 24;

    public static final String ERROR_DESCRIPTION = "Confirmation required";

    public ApiNeedConfirmationException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiNeedConfirmationException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
