// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiNotSupportedHttpMethodException extends ApiException {
    public static final Integer ERROR_CODE = 9999;

    public static final String ERROR_DESCRIPTION = "Not supported http method";

    public ApiNotSupportedHttpMethodException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiNotSupportedHttpMethodException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
