// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiOtpValidationNeedException extends ApiException {
    public static final Integer ERROR_CODE = 3303;

    public static final String ERROR_DESCRIPTION = "Otp app validation needed";

    public ApiOtpValidationNeedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiOtpValidationNeedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
