// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiPermissionException extends ApiException {
    public static final Integer ERROR_CODE = 7;

    public static final String ERROR_DESCRIPTION = "Permission to perform this action is denied";

    public ApiPermissionException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiPermissionException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
