// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiPasswordValidationNeedException extends ApiException {
    public static final Integer ERROR_CODE = 3302;

    public static final String ERROR_DESCRIPTION = "Password validation needed";

    public ApiPasswordValidationNeedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiPasswordValidationNeedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
