// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiParamTitleException extends ApiException {
    public static final Integer ERROR_CODE = 119;

    public static final String ERROR_DESCRIPTION = "Invalid title";

    public ApiParamTitleException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiParamTitleException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
