// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiPrettyCardsCardNotFoundException extends ApiException {
    public static final Integer ERROR_CODE = 1900;

    public static final String ERROR_DESCRIPTION = "Card not found";

    public ApiPrettyCardsCardNotFoundException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiPrettyCardsCardNotFoundException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
