// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiParamTimestampException extends ApiException {
    public static final Integer ERROR_CODE = 150;

    public static final String ERROR_DESCRIPTION = "Invalid timestamp";

    public ApiParamTimestampException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiParamTimestampException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
