// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiPollsPollIdException extends ApiException {
    public static final Integer ERROR_CODE = 251;

    public static final String ERROR_DESCRIPTION = "Invalid poll id";

    public ApiPollsPollIdException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiPollsPollIdException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
