// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiParamPhotoException extends ApiException {
    public static final Integer ERROR_CODE = 129;

    public static final String ERROR_DESCRIPTION = "Invalid photo";

    public ApiParamPhotoException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiParamPhotoException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
