// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiParamUserIdException extends ApiException {
    public static final Integer ERROR_CODE = 113;

    public static final String ERROR_DESCRIPTION = "Invalid user id";

    public ApiParamUserIdException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiParamUserIdException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
