// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiPhotoChangedException extends ApiException {
    public static final Integer ERROR_CODE = 1160;

    public static final String ERROR_DESCRIPTION = "Original photo was changed";

    public ApiPhotoChangedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiPhotoChangedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
