// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiParamGroupIdException extends ApiException {
    public static final Integer ERROR_CODE = 125;

    public static final String ERROR_DESCRIPTION = "Invalid group id";

    public ApiParamGroupIdException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiParamGroupIdException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
