// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiPrivateProfileException extends ApiException {
    public static final Integer ERROR_CODE = 30;

    public static final String ERROR_DESCRIPTION = "This profile is private";

    public ApiPrivateProfileException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiPrivateProfileException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
