// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiParamDocRestoreTimeoutException extends ApiException {
    public static final Integer ERROR_CODE = 1155;

    public static final String ERROR_DESCRIPTION = "Document was deleted too long ago";

    public ApiParamDocRestoreTimeoutException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiParamDocRestoreTimeoutException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
