// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiParamDocRestoreAccessException extends ApiException {
    public static final Integer ERROR_CODE = 1154;

    public static final String ERROR_DESCRIPTION = "Access to document restoring is denied";

    public ApiParamDocRestoreAccessException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiParamDocRestoreAccessException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
