// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiParamApiIdException extends ApiException {
    public static final Integer ERROR_CODE = 101;

    public static final String ERROR_DESCRIPTION = "Invalid application API ID";

    public ApiParamApiIdException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiParamApiIdException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
