// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiParamPhotosException extends ApiException {
    public static final Integer ERROR_CODE = 122;

    public static final String ERROR_DESCRIPTION = "Invalid photos";

    public ApiParamPhotosException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiParamPhotosException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
