// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiPollsAccessException extends ApiException {
    public static final Integer ERROR_CODE = 250;

    public static final String ERROR_DESCRIPTION = "Access to poll denied";

    public ApiPollsAccessException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiPollsAccessException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
