// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiParamDocDeleteAccessException extends ApiException {
    public static final Integer ERROR_CODE = 1151;

    public static final String ERROR_DESCRIPTION = "Access to document deleting is denied";

    public ApiParamDocDeleteAccessException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiParamDocDeleteAccessException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
