// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiParamDocTitleException extends ApiException {
    public static final Integer ERROR_CODE = 1152;

    public static final String ERROR_DESCRIPTION = "Invalid document title";

    public ApiParamDocTitleException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiParamDocTitleException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
