// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiRequestException extends ApiException {
    public static final Integer ERROR_CODE = 8;

    public static final String ERROR_DESCRIPTION = "Invalid request";

    public ApiRequestException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiRequestException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
