// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiRuntimeException extends ApiException {
    public static final Integer ERROR_CODE = 13;

    public static final String ERROR_DESCRIPTION = "Runtime error occurred during code invocation";

    public ApiRuntimeException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiRuntimeException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
