// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiStoryExpiredException extends ApiException {
    public static final Integer ERROR_CODE = 1600;

    public static final String ERROR_DESCRIPTION = "Story has already expired";

    public ApiStoryExpiredException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiStoryExpiredException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
