// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiSectionDisabledException extends ApiException {
    public static final Integer ERROR_CODE = 43;

    public static final String ERROR_DESCRIPTION = "This section is temporary unavailable";

    public ApiSectionDisabledException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiSectionDisabledException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
