// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiStickersNotFavoriteException extends ApiException {
    public static final Integer ERROR_CODE = 2102;

    public static final String ERROR_DESCRIPTION = "Stickers are not favorite";

    public ApiStickersNotFavoriteException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiStickersNotFavoriteException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
