// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiStickersNotPurchasedException extends ApiException {
    public static final Integer ERROR_CODE = 2100;

    public static final String ERROR_DESCRIPTION = "Stickers are not purchased";

    public ApiStickersNotPurchasedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiStickersNotPurchasedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
