// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiStatusNoAudioException extends ApiException {
    public static final Integer ERROR_CODE = 221;

    public static final String ERROR_DESCRIPTION = "User disabled track name broadcast";

    public ApiStatusNoAudioException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiStatusNoAudioException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
