// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiServerException extends ApiException {
    public static final Integer ERROR_CODE = 10;

    public static final String ERROR_DESCRIPTION = "Internal server error";

    public ApiServerException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiServerException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
