// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiTranslationsCantTranslateException extends ApiException {
    public static final Integer ERROR_CODE = 11101;

    public static final String ERROR_DESCRIPTION = "Can't translate.";

    public ApiTranslationsCantTranslateException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiTranslationsCantTranslateException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
