// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiTooManyListsException extends ApiException {
    public static final Integer ERROR_CODE = 1170;

    public static final String ERROR_DESCRIPTION = "Too many feed lists";

    public ApiTooManyListsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiTooManyListsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
