// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiTranslationsMultipleSourceLangException extends ApiException {
    public static final Integer ERROR_CODE = 11102;

    public static final String ERROR_DESCRIPTION = "Multiple source languages. Only one allowed.";

    public ApiTranslationsMultipleSourceLangException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiTranslationsMultipleSourceLangException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
