// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiTooManyException extends ApiException {
    public static final Integer ERROR_CODE = 6;

    public static final String ERROR_DESCRIPTION = "Too many requests per second";

    public ApiTooManyException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiTooManyException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
