// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiTimeoutException extends ApiException {
    public static final Integer ERROR_CODE = 36;

    public static final String ERROR_DESCRIPTION = "Method execution was interrupted due to timeout";

    public ApiTimeoutException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiTimeoutException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
