// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiUnknownApplicationException extends ApiException {
    public static final Integer ERROR_CODE = 38;

    public static final String ERROR_DESCRIPTION = "Unknown application";

    public ApiUnknownApplicationException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiUnknownApplicationException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
