// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiUnknownUserException extends ApiException {
    public static final Integer ERROR_CODE = 39;

    public static final String ERROR_DESCRIPTION = "Unknown user";

    public ApiUnknownUserException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiUnknownUserException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
