// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiUploadException extends ApiException {
    public static final Integer ERROR_CODE = 22;

    public static final String ERROR_DESCRIPTION = "Upload error";

    public ApiUploadException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiUploadException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
