// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiUserServiceDeactivatedException extends ApiException {
    public static final Integer ERROR_CODE = 3611;

    public static final String ERROR_DESCRIPTION = "Service is deactivated for user";

    public ApiUserServiceDeactivatedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiUserServiceDeactivatedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
