// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiUnknownException extends ApiException {
    public static final Integer ERROR_CODE = 1;

    public static final String ERROR_DESCRIPTION = "Unknown error occurred";

    public ApiUnknownException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiUnknownException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
