// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiUnknownGroupException extends ApiException {
    public static final Integer ERROR_CODE = 40;

    public static final String ERROR_DESCRIPTION = "Unknown group";

    public ApiUnknownGroupException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiUnknownGroupException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
