// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiUserDeactivatedException extends ApiException {
    public static final Integer ERROR_CODE = 3610;

    public static final String ERROR_DESCRIPTION = "User is deactivated";

    public ApiUserDeactivatedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiUserDeactivatedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
