// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiVideoCommentsClosedException extends ApiException {
    public static final Integer ERROR_CODE = 801;

    public static final String ERROR_DESCRIPTION = "Comments for this video are closed";

    public ApiVideoCommentsClosedException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiVideoCommentsClosedException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
