// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiVotesPermissionException extends ApiException {
    public static final Integer ERROR_CODE = 500;

    public static final String ERROR_DESCRIPTION = "Permission denied. You must enable votes processing in application settings";

    public ApiVotesPermissionException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiVotesPermissionException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
