// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiWallAddPostException extends ApiException {
    public static final Integer ERROR_CODE = 214;

    public static final String ERROR_DESCRIPTION = "Access to adding post denied";

    public ApiWallAddPostException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiWallAddPostException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
