// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiWallCheckLinkCantDetermineSourceException extends ApiException {
    public static final Integer ERROR_CODE = 3102;

    public static final String ERROR_DESCRIPTION = "Specified link is incorrect (can't find source)";

    public ApiWallCheckLinkCantDetermineSourceException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiWallCheckLinkCantDetermineSourceException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
