// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiWallAccessAddReplyException extends ApiException {
    public static final Integer ERROR_CODE = 213;

    public static final String ERROR_DESCRIPTION = "Access to status replies denied";

    public ApiWallAccessAddReplyException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiWallAccessAddReplyException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
