// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiWallAccessPostException extends ApiException {
    public static final Integer ERROR_CODE = 210;

    public static final String ERROR_DESCRIPTION = "Access to wall's post denied";

    public ApiWallAccessPostException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiWallAccessPostException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
