// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiWaitException extends ApiException {
    public static final Integer ERROR_CODE = 32;

    public static final String ERROR_DESCRIPTION = "Need wait";

    public ApiWaitException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiWaitException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
