// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiWallTooManyRecipientsException extends ApiException {
    public static final Integer ERROR_CODE = 220;

    public static final String ERROR_DESCRIPTION = "Too many recipients";

    public ApiWallTooManyRecipientsException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiWallTooManyRecipientsException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
