// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.exceptions;

import com.vk.api.sdk.objects.base.Error;

public class ApiWallAccessRepliesException extends ApiException {
    public static final Integer ERROR_CODE = 212;

    public static final String ERROR_DESCRIPTION = "Access to post comments denied";

    public ApiWallAccessRepliesException(Error error) {
        super(error.setErrorText(ERROR_DESCRIPTION));
    }

    public ApiWallAccessRepliesException() {
        super(new Error().setErrorCode(ERROR_CODE).setErrorText(ERROR_DESCRIPTION));
    }
}
