// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.utils.responses;

import com.vk.api.sdk.objects.utils.LinkChecked;

public class CheckLinkResponse extends LinkChecked {
}
