// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.messages;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;
import com.vk.api.sdk.objects.base.MessageError;

import java.util.Objects;

/**
 * GetInviteLinkByOwnerResponseItem object
 */
public class GetInviteLinkByOwnerResponseItem implements Validable {
    @SerializedName("error")
    private MessageError error;

    @SerializedName("link")
    private String link;

    /**
     * Entity: owner
     */
    @SerializedName("owner_id")
    @Required
    private Long ownerId;

    public MessageError getError() {
        return error;
    }

    public GetInviteLinkByOwnerResponseItem setError(MessageError error) {
        this.error = error;
        return this;
    }

    public String getLink() {
        return link;
    }

    public GetInviteLinkByOwnerResponseItem setLink(String link) {
        this.link = link;
        return this;
    }

    public Long getOwnerId() {
        return ownerId;
    }

    public GetInviteLinkByOwnerResponseItem setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(link, ownerId, error);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        GetInviteLinkByOwnerResponseItem getInviteLinkByOwnerResponseItem = (GetInviteLinkByOwnerResponseItem) o;
        return Objects.equals(ownerId, getInviteLinkByOwnerResponseItem.ownerId) &&
                Objects.equals(link, getInviteLinkByOwnerResponseItem.link) &&
                Objects.equals(error, getInviteLinkByOwnerResponseItem.error);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("GetInviteLinkByOwnerResponseItem{");
        sb.append("ownerId=").append(ownerId);
        sb.append(", link='").append(link).append("'");
        sb.append(", error=").append(error);
        sb.append('}');
        return sb.toString();
    }
}
