// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.messages;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

/**
 * Attachments type
 */
public enum HistoryMessageAttachmentType implements EnumParam<String> {
    @SerializedName("app_action")
    APP_ACTION("app_action"),

    @SerializedName("audio")
    AUDIO("audio"),

    @SerializedName("doc")
    DOC("doc"),

    @SerializedName("link")
    LINK("link"),

    @SerializedName("market")
    MARKET("market"),

    @SerializedName("photo")
    PHOTO("photo"),

    @SerializedName("video")
    VIDEO("video"),

    @SerializedName("wall")
    WALL("wall"),

    @SerializedName("graffiti")
    GRAFFITI("graffiti"),

    @SerializedName("audio_message")
    AUDIO_MESSAGE("audio_message");

    private final String value;

    HistoryMessageAttachmentType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toLowerCase();
    }
}
