// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.market;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

/**
 * Type of album
 */
public enum MarketAlbumType implements EnumParam<Integer> {
    @SerializedName("0")
    MARKET(0),

    @SerializedName("1")
    MARKET_SERVICES(1);

    private final Integer value;

    MarketAlbumType(Integer value) {
        this.value = value;
    }

    public Integer getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toString().toLowerCase();
    }
}
