// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.market;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

public enum MarketCategoryNestedInnerType implements EnumParam<String> {
    @SerializedName("market_market_category_nested")
    MARKET_MARKET_CATEGORY_NESTED("market_market_category_nested");

    private final String value;

    MarketCategoryNestedInnerType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toLowerCase();
    }
}
