// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.market;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;

import java.util.List;
import java.util.Objects;

/**
 * MarketCategoryTree object
 */
public class MarketCategoryTree implements Validable {
    @SerializedName("children")
    private List<MarketCategoryTree> children;

    /**
     * Icon name
     */
    @SerializedName("icon_name")
    private String iconName;

    /**
     * Category ID
     */
    @SerializedName("id")
    @Required
    private Integer id;

    /**
     * Category name
     */
    @SerializedName("name")
    @Required
    private String name;

    /**
     * Description for category's page. Used for SEO
     */
    @SerializedName("page_description")
    private String pageDescription;

    /**
     * Title for category's page. Used for SEO
     */
    @SerializedName("page_title")
    private String pageTitle;

    /**
     * SEO-friendly variant of category's name
     */
    @SerializedName("seo_name")
    private String seoName;

    /**
     * SEO-friendly URL to page with category's items
     */
    @SerializedName("url")
    private String url;

    @SerializedName("view")
    private MarketCategoryTreeView view;

    public List<MarketCategoryTree> getChildren() {
        return children;
    }

    public MarketCategoryTree setChildren(List<MarketCategoryTree> children) {
        this.children = children;
        return this;
    }

    public String getIconName() {
        return iconName;
    }

    public MarketCategoryTree setIconName(String iconName) {
        this.iconName = iconName;
        return this;
    }

    public Integer getId() {
        return id;
    }

    public MarketCategoryTree setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return name;
    }

    public MarketCategoryTree setName(String name) {
        this.name = name;
        return this;
    }

    public String getPageDescription() {
        return pageDescription;
    }

    public MarketCategoryTree setPageDescription(String pageDescription) {
        this.pageDescription = pageDescription;
        return this;
    }

    public String getPageTitle() {
        return pageTitle;
    }

    public MarketCategoryTree setPageTitle(String pageTitle) {
        this.pageTitle = pageTitle;
        return this;
    }

    public String getSeoName() {
        return seoName;
    }

    public MarketCategoryTree setSeoName(String seoName) {
        this.seoName = seoName;
        return this;
    }

    public String getUrl() {
        return url;
    }

    public MarketCategoryTree setUrl(String url) {
        this.url = url;
        return this;
    }

    public MarketCategoryTreeView getView() {
        return view;
    }

    public MarketCategoryTree setView(MarketCategoryTreeView view) {
        this.view = view;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(view, children, iconName, pageTitle, name, pageDescription, id, url, seoName);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        MarketCategoryTree marketCategoryTree = (MarketCategoryTree) o;
        return Objects.equals(view, marketCategoryTree.view) &&
                Objects.equals(children, marketCategoryTree.children) &&
                Objects.equals(pageTitle, marketCategoryTree.pageTitle) &&
                Objects.equals(name, marketCategoryTree.name) &&
                Objects.equals(seoName, marketCategoryTree.seoName) &&
                Objects.equals(id, marketCategoryTree.id) &&
                Objects.equals(iconName, marketCategoryTree.iconName) &&
                Objects.equals(url, marketCategoryTree.url) &&
                Objects.equals(pageDescription, marketCategoryTree.pageDescription);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("MarketCategoryTree{");
        sb.append("view=").append(view);
        sb.append(", children=").append(children);
        sb.append(", pageTitle='").append(pageTitle).append("'");
        sb.append(", name='").append(name).append("'");
        sb.append(", seoName='").append(seoName).append("'");
        sb.append(", id=").append(id);
        sb.append(", iconName='").append(iconName).append("'");
        sb.append(", url='").append(url).append("'");
        sb.append(", pageDescription='").append(pageDescription).append("'");
        sb.append('}');
        return sb.toString();
    }
}
