// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.market;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;

import java.util.Objects;

/**
 * PropertyVariant object
 */
public class PropertyVariant implements Validable {
    @SerializedName("id")
    @Required
    private Integer id;

    /**
     * Property name
     */
    @SerializedName("title")
    @Required
    private String title;

    /**
     * Property value corresponding to property type
     */
    @SerializedName("value")
    private String value;

    public Integer getId() {
        return id;
    }

    public PropertyVariant setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getTitle() {
        return title;
    }

    public PropertyVariant setTitle(String title) {
        this.title = title;
        return this;
    }

    public String getValue() {
        return value;
    }

    public PropertyVariant setValue(String value) {
        this.value = value;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, title, value);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PropertyVariant propertyVariant = (PropertyVariant) o;
        return Objects.equals(id, propertyVariant.id) &&
                Objects.equals(title, propertyVariant.title) &&
                Objects.equals(value, propertyVariant.value);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("PropertyVariant{");
        sb.append("id=").append(id);
        sb.append(", title='").append(title).append("'");
        sb.append(", value='").append(value).append("'");
        sb.append('}');
        return sb.toString();
    }
}
