// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.users.responses;

import com.vk.api.sdk.objects.users.UserFull;

public class GetResponse extends UserFull {
}
