// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.client;

import com.google.gson.Gson;
import com.vk.api.sdk.actions.Utils;
import com.vk.api.sdk.actions.*;
import org.apache.commons.lang3.StringUtils;

public class VkApiClient {
    private static final String API_VERSION = "5.199";

    private static final String API_ADDRESS = "https://api.vk.com/method/";

    private static final String OAUTH_ENDPOINT = "https://oauth.vk.com/";

    private static final Integer DEFAULT_RETRY_ATTEMPTS_INTERNAL_SERVER_ERROR_COUNT = 3;

    private TransportClient transportClient;

    private String apiEndpoint;

    private Gson gson;

    private String oAuthEndpoint;

    private Integer retryAttemptsInternalServerErrorCount;

    public VkApiClient(TransportClient transportClient) {
        this(transportClient, new GsonHolder().getGson(), DEFAULT_RETRY_ATTEMPTS_INTERNAL_SERVER_ERROR_COUNT);
    }

    public VkApiClient(TransportClient transportClient, Gson gson,
            int retryAttemptsInternalServerErrorCount) {
        this.transportClient = transportClient;
        this.gson = gson;
        this.retryAttemptsInternalServerErrorCount = retryAttemptsInternalServerErrorCount;

        if (StringUtils.isNoneEmpty(System.getProperty("api.host"))) {
            apiEndpoint = "https://" + System.getProperty("api.host") + "/method/";
        } else {
            apiEndpoint = API_ADDRESS;
        }

        if (StringUtils.isNoneEmpty(System.getProperty("oauth.host")))  {
            oAuthEndpoint = "https://" + System.getProperty("oauth.host") + "/";
        } else {
            oAuthEndpoint = OAUTH_ENDPOINT;
        }
    }

    public String getApiVersion() {
        return API_VERSION;
    }

    public TransportClient getTransportClient() {
        return this.transportClient;
    }

    public String getApiEndpoint() {
        return this.apiEndpoint;
    }

    public Gson getGson() {
        return this.gson;
    }

    public String getOAuthEndpoint() {
        return this.oAuthEndpoint;
    }

    public Integer getRetryAttemptsInternalServerErrorCount() {
        return this.retryAttemptsInternalServerErrorCount;
    }

    public Asr asr() {
        return new Asr(this);
    }

    public Notes notes() {
        return new Notes(this);
    }

    public Auth auth() {
        return new Auth(this);
    }

    public Fave fave() {
        return new Fave(this);
    }

    public Secure secure() {
        return new Secure(this);
    }

    public Photos photos() {
        return new Photos(this);
    }

    public Pages pages() {
        return new Pages(this);
    }

    public Docs docs() {
        return new Docs(this);
    }

    public GroupsLongPoll groupsLongPoll() {
        return new GroupsLongPoll(this);
    }

    public Stats stats() {
        return new Stats(this);
    }

    public LeadForms leadForms() {
        return new LeadForms(this);
    }

    public Translations translations() {
        return new Translations(this);
    }

    public Utils utils() {
        return new Utils(this);
    }

    public Donut donut() {
        return new Donut(this);
    }

    public Adsweb adsweb() {
        return new Adsweb(this);
    }

    public Bugtracker bugtracker() {
        return new Bugtracker(this);
    }

    public Gifts gifts() {
        return new Gifts(this);
    }

    public Likes likes() {
        return new Likes(this);
    }

    public AppWidgets appWidgets() {
        return new AppWidgets(this);
    }

    public Execute execute() {
        return new Execute(this);
    }

    public Friends friends() {
        return new Friends(this);
    }

    public Users users() {
        return new Users(this);
    }

    public Market market() {
        return new Market(this);
    }

    public Ads ads() {
        return new Ads(this);
    }

    public Messages messages() {
        return new Messages(this);
    }

    public Orders orders() {
        return new Orders(this);
    }

    public DownloadedGames downloadedGames() {
        return new DownloadedGames(this);
    }

    public Notifications notifications() {
        return new Notifications(this);
    }

    public Status status() {
        return new Status(this);
    }

    public LongPoll longPoll() {
        return new LongPoll(this);
    }

    public Upload upload() {
        return new Upload(this);
    }

    public Polls polls() {
        return new Polls(this);
    }

    public Storage storage() {
        return new Storage(this);
    }

    public Video video() {
        return new Video(this);
    }

    public Widgets widgets() {
        return new Widgets(this);
    }

    public Database database() {
        return new Database(this);
    }

    public Search search() {
        return new Search(this);
    }

    public Streaming streaming() {
        return new Streaming(this);
    }

    public Newsfeed newsfeed() {
        return new Newsfeed(this);
    }

    public Apps apps() {
        return new Apps(this);
    }

    public Stories stories() {
        return new Stories(this);
    }

    public Groups groups() {
        return new Groups(this);
    }

    public Store store() {
        return new Store(this);
    }

    public OAuth oAuth() {
        return new OAuth(this);
    }

    public Podcasts podcasts() {
        return new Podcasts(this);
    }

    public Calls calls() {
        return new Calls(this);
    }

    public PrettyCards prettyCards() {
        return new PrettyCards(this);
    }

    public Wall wall() {
        return new Wall(this);
    }

    public Account account() {
        return new Account(this);
    }

    public Board board() {
        return new Board(this);
    }
}
