// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.leadforms.responses;

import com.vk.api.sdk.objects.leadforms.Form;

public class GetResponse extends Form {
}
