// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.streaming.responses;

import com.vk.api.sdk.objects.streaming.Stats;

public class GetStatsResponse extends Stats {
}
