// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.notes.responses;

import com.vk.api.sdk.objects.notes.Note;

public class GetByIdResponse extends Note {
}
