// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.donut.responses;

import com.vk.api.sdk.objects.donut.DonatorSubscriptionInfo;

public class GetSubscriptionResponse extends DonatorSubscriptionInfo {
}
