// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.polls.responses;

import com.vk.api.sdk.objects.polls.Poll;

public class CreateResponse extends Poll {
}
