// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.polls.responses;

import com.vk.api.sdk.objects.polls.FieldsVoters;

public class GetVotersFieldsResponse extends FieldsVoters {
}
