// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.database;

import com.vk.api.sdk.objects.base.BaseObject;

public class SchoolClass extends BaseObject {
}
