// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.storage.responses;

import com.vk.api.sdk.objects.storage.Value;

public class GetResponse extends Value {
}
