// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.newsfeed;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

public enum ItemDigestFullItemInnerType implements EnumParam<String> {
    @SerializedName("newsfeed_item_digest_full_item")
    NEWSFEED_ITEM_DIGEST_FULL_ITEM("newsfeed_item_digest_full_item");

    private final String value;

    ItemDigestFullItemInnerType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toLowerCase();
    }
}
