// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.newsfeed;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

/**
 * Type of object from which to unsubscribe: 'note' - note, 'photo' - photo, 'post' - post on user wall or community wall, 'topic' - topic, 'video' - video
 */
public enum UnsubscribeType implements EnumParam<String> {
    @SerializedName("clip")
    CLIP("clip"),

    @SerializedName("market")
    MARKET("market"),

    @SerializedName("note")
    NOTE("note"),

    @SerializedName("photo")
    PHOTO("photo"),

    @SerializedName("post")
    POST("post"),

    @SerializedName("topic")
    TOPIC("topic"),

    @SerializedName("video")
    VIDEO("video");

    private final String value;

    UnsubscribeType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toLowerCase();
    }
}
