// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.database.responses;

import com.vk.api.sdk.objects.database.CityById;

public class GetCitiesByIdResponse extends CityById {
}
