// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.asr.responses;

import com.vk.api.sdk.objects.asr.Task;

public class CheckStatusResponse extends Task {
}
