// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.queries.stats;

import com.vk.api.sdk.client.AbstractQueryBuilder;
import com.vk.api.sdk.client.VkApiClient;
import com.vk.api.sdk.client.actors.UserActor;
import com.vk.api.sdk.objects.annotations.ApiParam;
import com.vk.api.sdk.objects.base.responses.OkResponse;
import com.vk.api.sdk.objects.stats.TrackVisitorType;

import java.util.Arrays;
import java.util.List;

/**
 * Query for Stats.trackVisitor method
 */
public class StatsTrackVisitorQuery extends AbstractQueryBuilder<StatsTrackVisitorQuery, OkResponse> {
    /**
     * Creates a AbstractQueryBuilder instance that can be used to build user api request with various parameters
     *
     * @param client VK API client
     * @param actor actor with access token
     */
    public StatsTrackVisitorQuery(VkApiClient client, UserActor actor) {
        super(client, "stats.trackVisitor", OkResponse.class);
        accessToken(actor.getAccessToken());
    }

    /**
     * Set type
     *
     * @param value value of "type" parameter. By default open.
     * @return a reference to this {@code AbstractQueryBuilder} object to fulfill the "Builder" pattern.
     */
    @ApiParam("type")
    public StatsTrackVisitorQuery type(TrackVisitorType value) {
        return unsafeParam("type", value);
    }

    @Override
    protected StatsTrackVisitorQuery getThis() {
        return this;
    }

    @Override
    protected List<String> essentialKeys() {
        return Arrays.asList("access_token");
    }
}
