// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.users;

import com.google.gson.*;
import com.vk.api.sdk.objects.groups.GroupFull;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.Map;

public interface SubscriptionsItem {
    default UserFull getUsersSubscriptionsItemAsUserFull() {
        return (UserFull) this;
    }

    default GroupFull getUsersSubscriptionsItemAsGroupFull() {
        return (GroupFull) this;
    }

    class Deserializer implements JsonDeserializer<SubscriptionsItem> {
        private static final String discriminatorField = "type";

        private static final Map<String, Class<? extends SubscriptionsItem>> subtypes = new HashMap<String, Class<? extends SubscriptionsItem>>() {{
        put("profile", UserFull.class);
        put("page", GroupFull.class);
        put("event", GroupFull.class);
        put("email", UserFull.class);
        put("group", GroupFull.class);
        }};

        @Override
        public SubscriptionsItem deserialize(JsonElement json, Type typeOfT,
                JsonDeserializationContext context) throws JsonParseException {
            String errorTrace = "";
            try {
                JsonObject data = json.getAsJsonObject();
                String resultSubtypeValue = data.get(discriminatorField).getAsString();
                if (subtypes.containsKey(resultSubtypeValue)) {
                    return context.deserialize(data, subtypes.get(resultSubtypeValue));
                } else {
                    throw new JsonParseException("There is no discriminator field in JSON-object", new com.vk.api.sdk.exceptions.UnexpectedOneOfSubtypeException(resultSubtypeValue, Deserializer.class, subtypes.keySet()));
                }
            } catch (Exception e) {
                // Failed to deserialize SubscriptionsItem object from JSON
                errorTrace = e.getLocalizedMessage();
            }
            throw new JsonParseException("Failed to deserialize SubscriptionsItem object from JSON" + errorTrace);
        }
    }
}
