// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.video;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;

import java.util.Objects;

/**
 * Video download availability settings
 */
public class Download implements Validable {
    /**
     * Information whether the video can be downloaded for offline view
     */
    @SerializedName("can_download_for_offline_view")
    private Boolean canDownloadForOfflineView;

    /**
     * Information whether the video can be downloaded to the device
     */
    @SerializedName("can_download_to_device")
    private Boolean canDownloadToDevice;

    public Boolean getCanDownloadForOfflineView() {
        return canDownloadForOfflineView;
    }

    public Download setCanDownloadForOfflineView(Boolean canDownloadForOfflineView) {
        this.canDownloadForOfflineView = canDownloadForOfflineView;
        return this;
    }

    public Boolean getCanDownloadToDevice() {
        return canDownloadToDevice;
    }

    public Download setCanDownloadToDevice(Boolean canDownloadToDevice) {
        this.canDownloadToDevice = canDownloadToDevice;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(canDownloadForOfflineView, canDownloadToDevice);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Download download = (Download) o;
        return Objects.equals(canDownloadForOfflineView, download.canDownloadForOfflineView) &&
                Objects.equals(canDownloadToDevice, download.canDownloadToDevice);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("Download{");
        sb.append("canDownloadForOfflineView=").append(canDownloadForOfflineView);
        sb.append(", canDownloadToDevice=").append(canDownloadToDevice);
        sb.append('}');
        return sb.toString();
    }
}