// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.video;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;

import java.net.URI;
import java.util.List;
import java.util.Objects;

/**
 * Video timeline preview thumbnails
 */
public class TimelineThumbs implements Validable {
    /**
     * Number of thumbnails per image
     */
    @SerializedName("count_per_image")
    private Integer countPerImage;

    /**
     * Number of thumbnails per row
     */
    @SerializedName("count_per_row")
    private Integer countPerRow;

    /**
     * Total number of thumbnails
     */
    @SerializedName("count_total")
    private Integer countTotal;

    /**
     * Height of a single thumbnail frame
     */
    @SerializedName("frame_height")
    private Integer frameHeight;

    /**
     * Width of a single thumbnail frame
     */
    @SerializedName("frame_width")
    private Integer frameWidth;

    /**
     * Frequency (in seconds) between thumbnail frames
     */
    @SerializedName("frequency")
    private Integer frequency;

    /**
     * Information whether the thumbnails belong to a UV (unified video) source
     */
    @SerializedName("is_uv")
    private Boolean isUv;

    /**
     * URLs of the thumbnail sprite images
     */
    @SerializedName("links")
    private List<URI> links;

    public Integer getCountPerImage() {
        return countPerImage;
    }

    public TimelineThumbs setCountPerImage(Integer countPerImage) {
        this.countPerImage = countPerImage;
        return this;
    }

    public Integer getCountPerRow() {
        return countPerRow;
    }

    public TimelineThumbs setCountPerRow(Integer countPerRow) {
        this.countPerRow = countPerRow;
        return this;
    }

    public Integer getCountTotal() {
        return countTotal;
    }

    public TimelineThumbs setCountTotal(Integer countTotal) {
        this.countTotal = countTotal;
        return this;
    }

    public Integer getFrameHeight() {
        return frameHeight;
    }

    public TimelineThumbs setFrameHeight(Integer frameHeight) {
        this.frameHeight = frameHeight;
        return this;
    }

    public Integer getFrameWidth() {
        return frameWidth;
    }

    public TimelineThumbs setFrameWidth(Integer frameWidth) {
        this.frameWidth = frameWidth;
        return this;
    }

    public Integer getFrequency() {
        return frequency;
    }

    public TimelineThumbs setFrequency(Integer frequency) {
        this.frequency = frequency;
        return this;
    }

    public Boolean getIsUv() {
        return isUv;
    }

    public TimelineThumbs setIsUv(Boolean isUv) {
        this.isUv = isUv;
        return this;
    }

    public List<URI> getLinks() {
        return links;
    }

    public TimelineThumbs setLinks(List<URI> links) {
        this.links = links;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(countPerImage, countPerRow, countTotal, frameHeight, frameWidth, frequency, isUv, links);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        TimelineThumbs timelineThumbs = (TimelineThumbs) o;
        return Objects.equals(countPerImage, timelineThumbs.countPerImage) &&
                Objects.equals(countPerRow, timelineThumbs.countPerRow) &&
                Objects.equals(countTotal, timelineThumbs.countTotal) &&
                Objects.equals(frameHeight, timelineThumbs.frameHeight) &&
                Objects.equals(frameWidth, timelineThumbs.frameWidth) &&
                Objects.equals(frequency, timelineThumbs.frequency) &&
                Objects.equals(isUv, timelineThumbs.isUv) &&
                Objects.equals(links, timelineThumbs.links);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("TimelineThumbs{");
        sb.append("countPerImage=").append(countPerImage);
        sb.append(", countPerRow=").append(countPerRow);
        sb.append(", countTotal=").append(countTotal);
        sb.append(", frameHeight=").append(frameHeight);
        sb.append(", frameWidth=").append(frameWidth);
        sb.append(", frequency=").append(frequency);
        sb.append(", isUv=").append(isUv);
        sb.append(", links=").append(links);
        sb.append('}');
        return sb.toString();
    }
}