// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.video;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;

import java.util.List;
import java.util.Objects;

/**
 * Video privacy settings (view/comment)
 */
public class VideoPrivacy implements Validable {
    /**
     * Privacy category (e.g. all, friends, only_me)
     */
    @SerializedName("category")
    private String category;

    /**
     * Information whether the privacy restriction is enabled
     */
    @SerializedName("is_enabled")
    private Boolean isEnabled;

    /**
     * Owners affected by the privacy setting
     */
    @SerializedName("owners")
    private Owners owners;

    public String getCategory() {
        return category;
    }

    public VideoPrivacy setCategory(String category) {
        this.category = category;
        return this;
    }

    public Boolean getIsEnabled() {
        return isEnabled;
    }

    public VideoPrivacy setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
        return this;
    }

    public Owners getOwners() {
        return owners;
    }

    public VideoPrivacy setOwners(Owners owners) {
        this.owners = owners;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(category, isEnabled, owners);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        VideoPrivacy videoPrivacy = (VideoPrivacy) o;
        return Objects.equals(category, videoPrivacy.category) &&
                Objects.equals(isEnabled, videoPrivacy.isEnabled) &&
                Objects.equals(owners, videoPrivacy.owners);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("VideoPrivacy{");
        sb.append("category='").append(category).append("'");
        sb.append(", isEnabled=").append(isEnabled);
        sb.append(", owners=").append(owners);
        sb.append('}');
        return sb.toString();
    }

    /**
     * Owners affected by a video privacy setting
     */
    public static class Owners implements Validable {
        /**
         * Ids of users/groups allowed by the privacy setting
         */
        @SerializedName("allowed")
        private List<Long> allowed;

        /**
         * Ids of users/groups excluded by the privacy setting
         */
        @SerializedName("excluded")
        private List<Long> excluded;

        public List<Long> getAllowed() {
            return allowed;
        }

        public Owners setAllowed(List<Long> allowed) {
            this.allowed = allowed;
            return this;
        }

        public List<Long> getExcluded() {
            return excluded;
        }

        public Owners setExcluded(List<Long> excluded) {
            this.excluded = excluded;
            return this;
        }

        @Override
        public int hashCode() {
            return Objects.hash(allowed, excluded);
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Owners owners = (Owners) o;
            return Objects.equals(allowed, owners.allowed) &&
                    Objects.equals(excluded, owners.excluded);
        }

        @Override
        public String toString() {
            final Gson gson = new Gson();
            return gson.toJson(this);
        }

        public String toPrettyString() {
            final StringBuilder sb = new StringBuilder("Owners{");
            sb.append("allowed=").append(allowed);
            sb.append(", excluded=").append(excluded);
            sb.append('}');
            return sb.toString();
        }
    }
}