// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.video;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;

import java.util.List;
import java.util.Objects;

/**
 * VideoFull object
 */
public class VideoFull extends Video implements Validable {
    /**
     * List of video episodes with timecodes
     */
    @SerializedName("episodes")
    private List<Episode> episodes;

    @SerializedName("files")
    private VideoFiles files;

    /**
     * Settings for live stream
     */
    @SerializedName("live_settings")
    private LiveSettings liveSettings;

    @SerializedName("trailer")
    private VideoFiles trailer;

    /**
     * Download availability settings of the video
     */
    @SerializedName("download")
    private Download download;

    /**
     * Privacy settings for commenting the video
     */
    @SerializedName("privacy_comment")
    private VideoPrivacy privacyComment;

    /**
     * Privacy settings for viewing the video
     */
    @SerializedName("privacy_view")
    private VideoPrivacy privacyView;

    /**
     * Timeline preview thumbnails of the video
     */
    @SerializedName("timeline_thumbs")
    private TimelineThumbs timelineThumbs;

    public List<Episode> getEpisodes() {
        return episodes;
    }

    public VideoFull setEpisodes(List<Episode> episodes) {
        this.episodes = episodes;
        return this;
    }

    public VideoFiles getFiles() {
        return files;
    }

    public VideoFull setFiles(VideoFiles files) {
        this.files = files;
        return this;
    }

    public LiveSettings getLiveSettings() {
        return liveSettings;
    }

    public VideoFull setLiveSettings(LiveSettings liveSettings) {
        this.liveSettings = liveSettings;
        return this;
    }

    public VideoFiles getTrailer() {
        return trailer;
    }

    public VideoFull setTrailer(VideoFiles trailer) {
        this.trailer = trailer;
        return this;
    }

    public Download getDownload() {
        return this.download;
    }

    public VideoFull setDownload(Download download) {
        this.download = download;
        return this;
    }

    public VideoPrivacy getPrivacyComment() {
        return this.privacyComment;
    }

    public VideoFull setPrivacyComment(VideoPrivacy privacyComment) {
        this.privacyComment = privacyComment;
        return this;
    }

    public VideoPrivacy getPrivacyView() {
        return this.privacyView;
    }

    public VideoFull setPrivacyView(VideoPrivacy privacyView) {
        this.privacyView = privacyView;
        return this;
    }

    public TimelineThumbs getTimelineThumbs() {
        return this.timelineThumbs;
    }

    public VideoFull setTimelineThumbs(TimelineThumbs timelineThumbs) {
        this.timelineThumbs = timelineThumbs;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(trailer, files, liveSettings, episodes, download, privacyComment, privacyView, timelineThumbs);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        VideoFull videoFull = (VideoFull) o;
        return Objects.equals(trailer, videoFull.trailer) &&
                Objects.equals(files, videoFull.files) &&
                Objects.equals(liveSettings, videoFull.liveSettings) &&
                Objects.equals(episodes, videoFull.episodes) &&
                Objects.equals(this.download, videoFull.download) &&
                Objects.equals(this.privacyComment, videoFull.privacyComment) &&
                Objects.equals(this.privacyView, videoFull.privacyView) &&
                Objects.equals(this.timelineThumbs, videoFull.timelineThumbs);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("VideoFull{");
        sb.append("trailer=").append(trailer);
        sb.append(", files=").append(files);
        sb.append(", liveSettings=").append(liveSettings);
        sb.append(", episodes=").append(episodes);
        sb.append(", download=").append(this.download);
        sb.append(", privacyComment=").append(this.privacyComment);
        sb.append(", privacyView=").append(this.privacyView);
        sb.append(", timelineThumbs=").append(this.timelineThumbs);
        sb.append('}');
        return sb.toString();
    }
}
