// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.video;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.base.Image;
import com.vk.api.sdk.objects.base.PropertyExists;

import java.util.Objects;

/**
 * VideoImage object
 */
public class VideoImage extends Image implements Validable {
    @SerializedName("size")
    private String size;

    @SerializedName("with_padding")
    private PropertyExists withPadding;

    public String getSize() {
        return size;
    }

    public VideoImage setSize(String size) {
        this.size = size;
        return this;
    }

    public boolean isWithPadding() {
        return withPadding == PropertyExists.PROPERTY_EXISTS;
    }

    @Override
    public int hashCode() {
        return Objects.hash(size, withPadding);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        VideoImage videoImage = (VideoImage) o;
        return Objects.equals(size, videoImage.size) &&
                Objects.equals(withPadding, videoImage.withPadding);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("VideoImage{");
        sb.append("size='").append(size).append("'");
        sb.append(", withPadding=").append(withPadding);
        sb.append('}');
        return sb.toString();
    }
}
