// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.orders.responses;

import com.vk.api.sdk.objects.orders.Amount;

public class GetAmountResponse extends Amount {
}
