// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.orders.responses;

import com.vk.api.sdk.objects.orders.Order;

public class GetResponse extends Order {
}
