// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.queries.friends;

import com.vk.api.sdk.client.AbstractQueryBuilder;
import com.vk.api.sdk.client.VkApiClient;
import com.vk.api.sdk.client.actors.UserActor;
import com.vk.api.sdk.objects.annotations.ApiParam;
import com.vk.api.sdk.objects.friends.responses.GetMutualTotalCountResponse;

import java.util.Arrays;
import java.util.List;

/**
 * Query for Friends.getMutual method
 */
public class FriendsGetMutualQueryWithTotalCount extends AbstractQueryBuilder<FriendsGetMutualQueryWithTotalCount, GetMutualTotalCountResponse> {
    /**
     * Creates a AbstractQueryBuilder instance that can be used to build user api request with various parameters
     *
     * @param client VK API client
     * @param actor actor with access token
     */
    public FriendsGetMutualQueryWithTotalCount(VkApiClient client, UserActor actor) {
        super(client, "friends.getMutual", GetMutualTotalCountResponse.class);
        accessToken(actor.getAccessToken());
    }

    /**
     * ID of the user whose friends will be checked against the friends of the user specified in 'target_uid'.
     *
     * @param value value of "source uid" parameter. Minimum is 1. Entity - owner
     *
     * @return a reference to this {@code AbstractQueryBuilder} object to fulfill the "Builder" pattern.
     */
    @ApiParam("source_uid")
    public FriendsGetMutualQueryWithTotalCount sourceUid(Long value) {
        return unsafeParam("source_uid", value);
    }

    /**
     * ID of the user whose friends will be checked against the friends of the user specified in 'source_uid'.
     *
     * @param value value of "target uid" parameter. Minimum is 1. Entity - owner
     *
     * @return a reference to this {@code AbstractQueryBuilder} object to fulfill the "Builder" pattern.
     */
    @ApiParam("target_uid")
    public FriendsGetMutualQueryWithTotalCount targetUid(Long value) {
        return unsafeParam("target_uid", value);
    }

    /**
     * Sort order: 'random' - random order
     *
     * @param value value of "order" parameter.
     * @return a reference to this {@code AbstractQueryBuilder} object to fulfill the "Builder" pattern.
     */
    @ApiParam("order")
    public FriendsGetMutualQueryWithTotalCount order(String value) {
        return unsafeParam("order", value);
    }

    /**
     * Number of mutual friends to return.
     *
     * @param value value of "count" parameter. Minimum is 0.
     * @return a reference to this {@code AbstractQueryBuilder} object to fulfill the "Builder" pattern.
     */
    @ApiParam("count")
    public FriendsGetMutualQueryWithTotalCount count(Integer value) {
        return unsafeParam("count", value);
    }

    /**
     * Offset needed to return a specific subset of mutual friends.
     *
     * @param value value of "offset" parameter. Minimum is 0.
     * @return a reference to this {@code AbstractQueryBuilder} object to fulfill the "Builder" pattern.
     */
    @ApiParam("offset")
    public FriendsGetMutualQueryWithTotalCount offset(Integer value) {
        return unsafeParam("offset", value);
    }

    /**
     * Return mutual friends total count
     *
     * @param value value of "need common count" parameter.
     * @return a reference to this {@code AbstractQueryBuilder} object to fulfill the "Builder" pattern.
     */
    @ApiParam("need_common_count")
    public FriendsGetMutualQueryWithTotalCount needCommonCount(Boolean value) {
        return unsafeParam("need_common_count", value);
    }

    /**
     * targetUids
     * IDs of the users whose friends will be checked against the friends of the user specified in 'source_uid'.
     *
     * @param value value of "target uids" parameter.
     * @return a reference to this {@code AbstractQueryBuilder} object to fulfill the "Builder" pattern.
     */
    @ApiParam("target_uids")
    public FriendsGetMutualQueryWithTotalCount targetUids(Long... value) {
        return unsafeParam("target_uids", value);
    }

    /**
     * IDs of the users whose friends will be checked against the friends of the user specified in 'source_uid'.
     *
     * @param value value of "target uids" parameter.
     * @return a reference to this {@code AbstractQueryBuilder} object to fulfill the "Builder" pattern.
     */
    @ApiParam("target_uids")
    public FriendsGetMutualQueryWithTotalCount targetUids(List<Long> value) {
        return unsafeParam("target_uids", value);
    }

    @Override
    protected FriendsGetMutualQueryWithTotalCount getThis() {
        return this;
    }

    @Override
    protected List<String> essentialKeys() {
        return Arrays.asList("access_token");
    }
}
