// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.apps;

import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.queries.EnumParam;

public enum CustomSnippetButton implements EnumParam<String> {
    @SerializedName("buy")
    BUY("buy"),

    @SerializedName("buy_ticket")
    BUY_TICKET("buy_ticket"),

    @SerializedName("contact")
    CONTACT("contact"),

    @SerializedName("create")
    CREATE("create"),

    @SerializedName("enroll")
    ENROLL("enroll"),

    @SerializedName("fill")
    FILL("fill"),

    @SerializedName("go")
    GO("go"),

    @SerializedName("open")
    OPEN("open"),

    @SerializedName("play")
    PLAY("play");

    private final String value;

    CustomSnippetButton(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return value.toLowerCase();
    }
}
