// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.store;

import com.vk.api.sdk.objects.stickers.ImageSet;

public class ProductIcon extends ImageSet {
}
