// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.ads.responses;

import com.vk.api.sdk.objects.ads.TargSuggestionsCities;

public class GetSuggestionsCitiesResponse extends TargSuggestionsCities {
}
